services:
  unit_tests_74:
    build:
      context: .
      dockerfile: php74.tests.Dockerfile
    hostname: csrf_protector_library_tests74
    environment:
      - Environment=testing
    volumes:
      - ./build:/var/app/build
  unit_tests_82:
    build:
      context: .
      dockerfile: php82.tests.Dockerfile
    hostname: csrf_protector_library_tests82
    environment:
      - Environment=testing
    volumes:
      - ./build:/var/app/build
